language: node_js
sudo: required
dist: trusty
node_js:
  - 10.9.0
cache:
  yarn: true
  directories:
    - './node_modules'
before_script:
  - yarn build ngx-picture
  - yarn build --prod
script:
  - yarn lint
  - yarn test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
before_deploy:
  - cd $TRAVIS_BUILD_DIR/dist/ngx-picture
deploy:
  - provider: npm
    email: mr.alexander.nickel@gmail.com
    skip_cleanup: true
    api_key:
      secure: eXNLzng3X1DpVDF6nBPpCOWi4Naq+B63m0EaZOn8I3rpNrdJe1QGBp8PZE2kUNDdDCE5X2SSrEteFOhGc6mhKRLWo/zxsg4+vKXGkStQIekeVZYf4+eepggrny7aVxxCZXib1m4kK20z/e03M8HHwRlKTt52rNNr88ucCkkNp+xhD0FcHVZ1AYSz/ft0p0B8/Dzeaps7vKMGk2C1AON2jUpd499g/rLRoZgz6zVwjHvRXv03pXSldhRVys4cLtf4pSNdbPs3FfhDTFZgAo8tIDK5BnPRdKGt4Tsn1NyqP26jNsACiI4UsdEOUfY9AT2Y0r4BiO1bvym0xOp/unut6wyPObfNiMDQERk3ATISBvIuUtlCwN8gTv4V3iTe9QnBfMFS6mKAseG6Qp6Klp5YrokPhS8h1xAOzQcARxe00aZ3zeyDPkqMf9F/nzmQzcmGwd6Jk3JaB7lmNdEXW4c+pDcL4sGi9SYcohHQUcTxKLxDrFp+gvOjnQ87HbJh/StoHO13bZ+O/z0hxeMAiALTyxzEyUzqKsiDBVDR+6TUA8CCEkkeL3sFGAWpmB6xufF6x3joG/2WyO7hpzn/wa1+fgRHLeT3uU3kSM2YRq4jxnkNQ+uzm8vI+U/f/d22yORDynhcbPyyscrbr18Jn+iGZ6Njtf6ideJ0iwiQsWAjshw=
    on:
      repo: mralexandernickel/ngx-picture
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: dist/ngx-picture-demo
    on:
      branch: master
